# Generated by Django 6.1 on 2026-10-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
